services:
  backend-services:
    container_name: ${PROJECT_NAME}-backend
    hostname : ${PROJECT_NAME}
    build:
      context: ./Backend
      dockerfile: Dockerfile 
    ports: 
      - "${BACKEND_PORT_MAP}:8000"
    volumes: 
      - ./Backend:/app
    env_file:
      - .env 
    restart: unless-stopped

  frontend-services:
    container_name: ${PROJECT_NAME}-frontend
    hostname: ${PROJECT_NAME}-frontend
    build:
      context: ./Frontend
      dockerfile: Dockerfile 
    ports:
      - "${WEB_PORT_MAP}:3000"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=https://warungku.backend.projectsdev.site
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
      - WDS_SOCKET_PORT=0
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
    depends_on: 
      - backend-services