services:
  backend-services:
    build:
      context: ./Backend
      dockerfile: Dockerfile 
    container_name: warungku_backend
    ports: 
      - "8001:8000"
    volumes: 
      - ./Backend:/app
    env_file:
      - .env 
    restart: unless-stopped

  frontend-services:
    build:
      context: ./Frontend
      dockerfile: Dockerfile 
    container_name: warungku_frontend
    ports:
      - "3001:3000"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=http://backend-services:8000
    depends_on: 
      - backend-services