services:
  backend-services:
    build:
      context: ./Backend
      dockerfile: Dockerfile 
    container_name: warungku_backend
    ports: 
      - "8001:8000"
    volumes: 
      - ./Backend:/app
    env_file:
      - .env 
    restart: unless-stopped

  frontend-services:
    build:
      context: ./Frontend
      dockerfile: Dockerfile 
    container_name: warungku_frontend
    ports:
      - "3001:3000"
    volumes:
      - ./Frontend:/app
      - /app/node_modules
    environment:
      - REACT_APP_API_URL=https://warungku.backend.projectsdev.site
      - CHOKIDAR_USEPOLLING=true
      - HOST=0.0.0.0
      - WDS_SOCKET_PORT=0
      - DANGEROUSLY_DISABLE_HOST_CHECK=true
    depends_on: 
      - backend-services